version: '3.8'

services:
  # Questo servizio postgres esiste già
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: la-tua-password-segreta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- SEZIONE AGGIUNTA ---
  pgadmin:
    # Immagine ufficiale di pgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      # Credenziali per accedere a pgAdmin
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      # Esponiamo l'interfaccia web di pgAdmin sulla porta 8080
      - "8080:80"
    # Dice a Docker di avviare prima il servizio 'postgres'
    depends_on:
      - postgres

volumes:
  pgdata:
